# Generated by Django 3.1.4 on 2020-12-14 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('token', models.CharField(max_length=32)),
                ('sim', models.CharField(max_length=11)),
                ('fio', models.CharField(max_length=80)),
                ('passport', models.CharField(max_length=10)),
                ('role', models.ForeignKey(default=3, on_delete=django.db.models.deletion.RESTRICT, to='core.role')),
            ],
        ),
    ]
