# Generated by Django 3.1.4 on 2020-12-19 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.RESTRICT, to='core.role', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='person',
            name='token',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Токен'),
        ),
    ]
