# Generated by Django 3.1.4 on 2020-12-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201219_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.AlterModelOptions(
            name='operator',
            options={'verbose_name': 'Оператор связи', 'verbose_name_plural': 'Операторы связи'},
        ),
        migrations.AlterField(
            model_name='person',
            name='sim',
            field=models.CharField(max_length=11, unique=True, verbose_name='Номер телефона SIM-карты (10 знаков, без +7)'),
        ),
    ]
