# Generated by Django 3.1.4 on 2020-12-24 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201224_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='core.company', verbose_name='Компания'),
            preserve_default=False,
        ),
    ]
