# Generated by Django 3.1.4 on 2021-01-01 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_region_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
        migrations.RemoveField(
            model_name='person',
            name='role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
