# Generated by Django 3.1.4 on 2021-01-04 01:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210101_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='balans',
            field=models.IntegerField(default=0, verbose_name='Баланс'),
        ),
        migrations.AddField(
            model_name='person',
            name='monthly_payment',
            field=models.IntegerField(default=500, verbose_name='Платёж в месяц'),
        ),
        migrations.AddField(
            model_name='person',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата следующего платежа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='login',
            field=models.CharField(editable=False, max_length=30, unique=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='person',
            name='password',
            field=models.CharField(editable=False, max_length=30, verbose_name='Пароль'),
        ),
    ]
