# Generated by Django 3.1.4 on 2021-01-14 16:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210104_0446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма платежа')),
                ('datetime', models.DateTimeField(default=datetime.datetime(2021, 1, 14, 19, 53, 48, 633808), verbose_name='Дата платежа')),
                ('status', models.CharField(default='in_progress', max_length=20, verbose_name='Статус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.person', verbose_name='Пользователь')),
            ],
        ),
    ]
