# Generated by Django 3.1.4 on 2021-01-14 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210114_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 14, 20, 1, 57, 197738), verbose_name='Дата платежа'),
        ),
    ]
