# Generated by Django 3.1.4 on 2021-01-16 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210114_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='balans',
            new_name='balance',
        ),
        migrations.AlterField(
            model_name='payment',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 16, 12, 2, 26, 145544), verbose_name='Дата платежа'),
        ),
        migrations.AlterField(
            model_name='person',
            name='payment_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 16, 12, 2, 26, 144543), verbose_name='Дата следующего платежа'),
        ),
    ]
